server:
  dev:
    enabled: true
    devRootToken: "root"
  
  service:
    type: ClusterIP
    port: 8200

  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 500m

injector:
  enabled: false

ui:
  enabled: true
  serviceType: NodePort
  serviceNodePort: 30200